### ISSUE TITLE
outline for golang and bash

### ISSUE THREAD

**Issue by Shane-XB-Qian** [ubaldot/vim-outline#3]
if you not mind, wish you can add outline for golang and bash as well.

// too late to me, i am going to zzz...... thx. :-)
PR #1 and #2 is ready for merge if you are ok.

**Comment by ubaldot** [comment]
I'll pull the changes and test :) 
Thanks for the support! 

Yes, add golang and bash, please. 
Keep. in mind that you can PreProcess your buffer before passing through the standard regex filters. ;-) 
Look at Python example. 

Thanks again and goodnight!
